// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	AssignGameRoles(ctx context.Context, arg AssignGameRolesParams) error
	CreateGame(ctx context.Context) (Game, error)
	CreateGameLogs(ctx context.Context, arg CreateGameLogsParams) error
	FinishGame(ctx context.Context, arg FinishGameParams) error
	PlayingGame(ctx context.Context, playerID string) (Game, error)
}

var _ Querier = (*Queries)(nil)
