version: 2
updates:
  - package-ecosystem: npm
    directory: /communication
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /core
    schedule:
      interval: weekly
