version: "3.8"

services:
    app:
        image: werewolf-server:dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 8080:8080
        volumes:
            - ./:/app
            - .docker/go/pkg/mod:/go/pkg/mod
        networks:
            - cassandra-network
        restart: unless-stopped

    cassandra1:
        image: cassandra:3.11.14
        volumes:
            - .docker/cassandra/cassandra1.yaml:/etc/cassandra/cassandra.yaml
            - .docker/cassandra/data/n1:/var/lib/cassandra
        networks:
            - cassandra-network
        restart: unless-stopped
    #
    # cassandra2:
    #     image: cassandra:3.11.14
    #     volumes:
    #         - .docker/cassandra/cassandra2.yaml:/etc/cassandra/cassandra.yaml
    #         - .docker/cassandra/data/n2:/var/lib/cassandra
    #     environment:
    #         - CASSANDRA_SEEDS=cassandra1
    #     networks:
    #         - cassandra-network
    #     restart: unless-stopped

networks:
    cassandra-network:
