// Code generated by MockGen. DO NOT EDIT.
// Source: game/contract/game.go

// Package gamemock is a generated GoMock package.
package gamemock

import (
	reflect "reflect"
	contract "uwwolf/game/contract"
	types "uwwolf/game/types"

	gomock "github.com/golang/mock/gomock"
)

// MockGame is a mock of Game interface.
type MockGame struct {
	ctrl     *gomock.Controller
	recorder *MockGameMockRecorder
}

// MockGameMockRecorder is the mock recorder for MockGame.
type MockGameMockRecorder struct {
	mock *MockGame
}

// NewMockGame creates a new mock instance.
func NewMockGame(ctrl *gomock.Controller) *MockGame {
	mock := &MockGame{ctrl: ctrl}
	mock.recorder = &MockGameMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGame) EXPECT() *MockGameMockRecorder {
	return m.recorder
}

// Finish mocks base method.
func (m *MockGame) Finish() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finish")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Finish indicates an expected call of Finish.
func (mr *MockGameMockRecorder) Finish() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finish", reflect.TypeOf((*MockGame)(nil).Finish))
}

// ID mocks base method.
func (m *MockGame) ID() types.GameID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(types.GameID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockGameMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockGame)(nil).ID))
}

// KillPlayer mocks base method.
func (m *MockGame) KillPlayer(playerID types.PlayerID, isExited bool) contract.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KillPlayer", playerID, isExited)
	ret0, _ := ret[0].(contract.Player)
	return ret0
}

// KillPlayer indicates an expected call of KillPlayer.
func (mr *MockGameMockRecorder) KillPlayer(playerID, isExited interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillPlayer", reflect.TypeOf((*MockGame)(nil).KillPlayer), playerID, isExited)
}

// Play mocks base method.
func (m *MockGame) Play(playerID types.PlayerID, req types.ActivateAbilityRequest) types.ActionResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Play", playerID, req)
	ret0, _ := ret[0].(types.ActionResponse)
	return ret0
}

// Play indicates an expected call of Play.
func (mr *MockGameMockRecorder) Play(playerID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Play", reflect.TypeOf((*MockGame)(nil).Play), playerID, req)
}

// Player mocks base method.
func (m *MockGame) Player(playerID types.PlayerID) contract.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Player", playerID)
	ret0, _ := ret[0].(contract.Player)
	return ret0
}

// Player indicates an expected call of Player.
func (mr *MockGameMockRecorder) Player(playerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Player", reflect.TypeOf((*MockGame)(nil).Player), playerID)
}

// PlayerIDsWithFactionID mocks base method.
func (m *MockGame) PlayerIDsWithFactionID(factionID types.FactionID, onlyAlive bool) []types.PlayerID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerIDsWithFactionID", factionID, onlyAlive)
	ret0, _ := ret[0].([]types.PlayerID)
	return ret0
}

// PlayerIDsWithFactionID indicates an expected call of PlayerIDsWithFactionID.
func (mr *MockGameMockRecorder) PlayerIDsWithFactionID(factionID, onlyAlive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerIDsWithFactionID", reflect.TypeOf((*MockGame)(nil).PlayerIDsWithFactionID), factionID, onlyAlive)
}

// PlayerIDsWithRoleID mocks base method.
func (m *MockGame) PlayerIDsWithRoleID(roleID types.RoleID) []types.PlayerID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerIDsWithRoleID", roleID)
	ret0, _ := ret[0].([]types.PlayerID)
	return ret0
}

// PlayerIDsWithRoleID indicates an expected call of PlayerIDsWithRoleID.
func (mr *MockGameMockRecorder) PlayerIDsWithRoleID(roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerIDsWithRoleID", reflect.TypeOf((*MockGame)(nil).PlayerIDsWithRoleID), roleID)
}

// PlayerIDsWithoutFactionID mocks base method.
func (m *MockGame) PlayerIDsWithoutFactionID(factionID types.FactionID, onlyAlive bool) []types.PlayerID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerIDsWithoutFactionID", factionID, onlyAlive)
	ret0, _ := ret[0].([]types.PlayerID)
	return ret0
}

// PlayerIDsWithoutFactionID indicates an expected call of PlayerIDsWithoutFactionID.
func (mr *MockGameMockRecorder) PlayerIDsWithoutFactionID(factionID, onlyAlive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerIDsWithoutFactionID", reflect.TypeOf((*MockGame)(nil).PlayerIDsWithoutFactionID), factionID, onlyAlive)
}

// Players mocks base method.
func (m *MockGame) Players() map[types.PlayerID]contract.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Players")
	ret0, _ := ret[0].(map[types.PlayerID]contract.Player)
	return ret0
}

// Players indicates an expected call of Players.
func (mr *MockGameMockRecorder) Players() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Players", reflect.TypeOf((*MockGame)(nil).Players))
}

// Poll mocks base method.
func (m *MockGame) Poll(factionID types.FactionID) contract.Poll {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", factionID)
	ret0, _ := ret[0].(contract.Poll)
	return ret0
}

// Poll indicates an expected call of Poll.
func (mr *MockGameMockRecorder) Poll(factionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockGame)(nil).Poll), factionID)
}

// Prepare mocks base method.
func (m *MockGame) Prepare() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Prepare indicates an expected call of Prepare.
func (mr *MockGameMockRecorder) Prepare() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockGame)(nil).Prepare))
}

// Scheduler mocks base method.
func (m *MockGame) Scheduler() contract.Scheduler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scheduler")
	ret0, _ := ret[0].(contract.Scheduler)
	return ret0
}

// Scheduler indicates an expected call of Scheduler.
func (mr *MockGameMockRecorder) Scheduler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scheduler", reflect.TypeOf((*MockGame)(nil).Scheduler))
}

// Start mocks base method.
func (m *MockGame) Start() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockGameMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockGame)(nil).Start))
}

// StatusID mocks base method.
func (m *MockGame) StatusID() types.GameStatusID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusID")
	ret0, _ := ret[0].(types.GameStatusID)
	return ret0
}

// StatusID indicates an expected call of StatusID.
func (mr *MockGameMockRecorder) StatusID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusID", reflect.TypeOf((*MockGame)(nil).StatusID))
}
