DROP TABLE IF EXISTS game_logs;
DROP TABLE IF EXISTS role_assignments;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS actions;
DROP TABLE IF EXISTS factions;
