app:
  debug: true
  env: development
  port: 8080
database:
  host: postgres
  port: 5432
  username: ww_username
  password: ww_password
  database: ww_db
redis:
  sentinel_addresses:
    - redis:5000
    - redis:5001
    - redis:5002
  master_name: mymaster
  username: default
  password: redis_password
game:
  min_capacity: 5
  max_capacity: 20
  preparation_duration: 10s
  min_turn_duration: 20s
  max_turn_duration: 60s
  min_discussion_duration: 40s
  max_discussion_duration: 360s
