app:
  debug: true
  env: development
  port: 8080
postgres:
  host: postgres
  port: 5432
  username: ww_username
  password: ww_password
  database: ww_db
  pollSize: 10
redis:
  sentinelAddresses:
    - redis:5000
    - redis:5001
    - redis:5002
  masterName: mymaster
  username: default
  password: redis_password
  pollSize: 10
game:
  minCapacity: 4
  maxCapacity: 20
  preparationDuration: 10s
  minTurnDuration: 20s
  maxTurnDuration: 60s
  minDiscussionDuration: 40s
  maxDiscussionDuration: 360s
firebase:
  productId:
  privateKey:
  email:
