version: "3.8"

services:
    app:
        image: werewolf-core:dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 8080:8080
        volumes:
            - ./:/app
            - .docker/go/pkg/mod:/go/pkg/mod
        depends_on:
            - postgres
            - redis
        networks:
            - postgres-network
            - redis-network
        restart: unless-stopped

    postgres:
        image: postgres:15.2-alpine
        environment:
            - POSTGRES_USER=ww_username
            - POSTGRES_PASSWORD=ww_password
            - POSTGRES_DB=ww_db
        volumes:
            - .docker/postgres/data:/var/lib/postgresql/data
        networks:
            - postgres-network
        restart: unless-stopped

    adminer:
        image: adminer
        ports:
            - 8081:8080
        networks:
            - postgres-network
        restart: unless-stopped

    redis:
        image: redis:7.0.9-alpine
        environment:
            - REDIS_PASSWORD=ww_password
        volumes:
            - .docker/redis/data:/data
        command: redis-server --requirepass ww_password
        networks:
            - redis-network
        restart: unless-stopped

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: ww_password
        ports:
            - 8082:8081
        networks:
            - redis-network
        depends_on:
            - redis
        restart: unless-stopped

networks:
    postgres-network:
    redis-network:
