// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Action struct {
	ID int16 `json:"id"`
}

type Faction struct {
	ID int16 `json:"id"`
}

type Game struct {
	ID               int64         `json:"id"`
	WinningFactionID sql.NullInt16 `json:"winning_faction_id"`
	CreatedAt        time.Time     `json:"created_at"`
	FinishedAt       sql.NullTime  `json:"finished_at"`
}

type GameLog struct {
	GameID   int64  `json:"game_id"`
	RoundID  int16  `json:"round_id"`
	ActorID  string `json:"actor_id"`
	RoleID   int16  `json:"role_id"`
	ActionID int16  `json:"action_id"`
	TargetID string `json:"target_id"`
}

type Player struct {
	ID string `json:"id"`
}

type Role struct {
	ID int16 `json:"id"`
}

type RoleAssignment struct {
	GameID    int64         `json:"game_id"`
	RoleID    sql.NullInt16 `json:"role_id"`
	FactionID sql.NullInt16 `json:"faction_id"`
	PlayerID  string        `json:"player_id"`
}
