// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/game/logic/contract/poll.go

// Package mock_game_logic is a generated GoMock package.
package mock_game_logic

import (
	reflect "reflect"
	contract "uwwolf/internal/app/game/logic/contract"
	types "uwwolf/internal/app/game/logic/types"

	gomock "github.com/golang/mock/gomock"
)

// MockPoll is a mock of Poll interface.
type MockPoll struct {
	ctrl     *gomock.Controller
	recorder *MockPollMockRecorder
}

// MockPollMockRecorder is the mock recorder for MockPoll.
type MockPollMockRecorder struct {
	mock *MockPoll
}

// NewMockPoll creates a new mock instance.
func NewMockPoll(ctrl *gomock.Controller) *MockPoll {
	mock := &MockPoll{ctrl: ctrl}
	mock.recorder = &MockPollMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoll) EXPECT() *MockPollMockRecorder {
	return m.recorder
}

// AddCandidates mocks base method.
func (m *MockPoll) AddCandidates(candidateIDs ...types.PlayerId) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range candidateIDs {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddCandidates", varargs...)
}

// AddCandidates indicates an expected call of AddCandidates.
func (mr *MockPollMockRecorder) AddCandidates(candidateIDs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCandidates", reflect.TypeOf((*MockPoll)(nil).AddCandidates), candidateIDs...)
}

// AddElectors mocks base method.
func (m *MockPoll) AddElectors(electorIDs ...types.PlayerId) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range electorIDs {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddElectors", varargs...)
}

// AddElectors indicates an expected call of AddElectors.
func (mr *MockPollMockRecorder) AddElectors(electorIDs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddElectors", reflect.TypeOf((*MockPoll)(nil).AddElectors), electorIDs...)
}

// CanVote mocks base method.
func (m *MockPoll) CanVote(electorID types.PlayerId) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanVote", electorID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanVote indicates an expected call of CanVote.
func (mr *MockPollMockRecorder) CanVote(electorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanVote", reflect.TypeOf((*MockPoll)(nil).CanVote), electorID)
}

// Close mocks base method.
func (m *MockPoll) Close() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPollMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPoll)(nil).Close))
}

// IsOpen mocks base method.
func (m *MockPoll) IsOpen() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOpen")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOpen indicates an expected call of IsOpen.
func (mr *MockPollMockRecorder) IsOpen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOpen", reflect.TypeOf((*MockPoll)(nil).IsOpen))
}

// Open mocks base method.
func (m *MockPoll) Open() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockPollMockRecorder) Open() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockPoll)(nil).Open))
}

// Record mocks base method.
func (m *MockPoll) Record(round types.Round) contract.PollRecord {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", round)
	ret0, _ := ret[0].(contract.PollRecord)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockPollMockRecorder) Record(round interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockPoll)(nil).Record), round)
}

// RemoveCandidate mocks base method.
func (m *MockPoll) RemoveCandidate(candidateID types.PlayerId) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCandidate", candidateID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RemoveCandidate indicates an expected call of RemoveCandidate.
func (mr *MockPollMockRecorder) RemoveCandidate(candidateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCandidate", reflect.TypeOf((*MockPoll)(nil).RemoveCandidate), candidateID)
}

// RemoveElector mocks base method.
func (m *MockPoll) RemoveElector(electorID types.PlayerId) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveElector", electorID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RemoveElector indicates an expected call of RemoveElector.
func (mr *MockPollMockRecorder) RemoveElector(electorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveElector", reflect.TypeOf((*MockPoll)(nil).RemoveElector), electorID)
}

// SetWeight mocks base method.
func (m *MockPoll) SetWeight(electorID types.PlayerId, weight uint) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWeight", electorID, weight)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetWeight indicates an expected call of SetWeight.
func (mr *MockPollMockRecorder) SetWeight(electorID, weight interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWeight", reflect.TypeOf((*MockPoll)(nil).SetWeight), electorID, weight)
}

// Vote mocks base method.
func (m *MockPoll) Vote(electorID, candidateID types.PlayerId) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vote", electorID, candidateID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Vote indicates an expected call of Vote.
func (mr *MockPollMockRecorder) Vote(electorID, candidateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vote", reflect.TypeOf((*MockPoll)(nil).Vote), electorID, candidateID)
}
