/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatBox: typeof import('./components/room/ChatBox.vue')['default']
    JoinedPlayerList: typeof import('./components/room/JoinedPlayerList.vue')['default']
    OAuth: typeof import('./components/auth/OAuth.vue')['default']
    PickedRoleList: typeof import('./components/room/PickedRoleList.vue')['default']
    Role: typeof import('./components/room/Role.vue')['default']
    RoleCard: typeof import('./components/RoleCard.vue')['default']
    RoleList: typeof import('./components/room/RoleList.vue')['default']
    RoleSummaryCard: typeof import('./components/RoleSummaryCard.vue')['default']
    RoomChatBox: typeof import('./components/room/RoomChatBox.vue')['default']
    RoomSettings: typeof import('./components/room/RoomSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/room/Settings.vue')['default']
  }
}
