# https://game.ci/docs/github/builder
name: client

on:
  push:
    branches:
      - main
    paths:
      - client/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: client/Werewolf/Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-MyProjectName-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: client/Werewolf
          customParameters: -WebGLCompressionFormat Disabled

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

