name: core

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/core.yml
      - core/**
      - '!core/.vscode/**'
      - '!core/docs/**'
      - '!core/.docker/**'
      - '!core/.editorconfig'
      - '!core/.gitignore'
      - '!core/**.md'
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/core.yml
      - core/**
      - '!core/.vscode/**'
      - '!core/docs/**'
      - '!core/.docker/**'
      - '!core/.editorconfig'
      - '!core/.gitignore'
      - '!core/**.md'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18.0'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: core
          args: --tests=false
          skip-pkg-cache: false

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18.0'

      - name: Get golang store directory
        id: go-pkg-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(go env GOPATH)" >> $GITHUB_OUTPUT

      - name: Setup pkg cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-pkg-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-go-pkg-${{ hashFiles('core/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-pkg-

      - name: Install packages
        working-directory: core
        run: go mod download

      - name: Create cofig
        working-directory: core
        run: cp config.example.yaml config.yaml

      - name: Run test
        working-directory: core
        run: go test ./... -cover

  build:
    if: github.event_name == 'push'

    needs:
      - lint
      - test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}

      - name: Create image tags
        id: tags
        run: |
          case ${{ github.ref }} in

            refs/heads/main)
              echo "TAGS=\
              ghcr.io/${{ github.repository }}-core:staging-latest, \
              ghcr.io/${{ github.repository }}-core:staging-${{ github.sha }}" >> $GITHUB_OUTPUT
              ;;

            refs/heads/production)
              echo "TAGS=\
              ghcr.io/${{ github.repository }}-core:staging-latest, \
              ghcr.io/${{ github.repository }}-core:staging-${{ github.sha }}" >> $GITHUB_OUTPUT
              ;;

            *)
              echo "This branch can't be built"
              ;;
          esac

      - name: Build and push
        if: steps.tags.outputs.TAGS != ''
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./core
          tags: ${{ steps.tags.outputs.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
